import { MediaItem, LibraryItem } from '../shared/types';

export const SEED_MEDIA: MediaItem[] = [
  {
    id: 'seed_top_gun_maverick',
    canonicalTitle: 'Top Gun: Maverick',
    type: 'movie',
    year: 2022,
    genres: ['Action', 'Drama'],
    ratings: [{ score: 8.3, provider: 'tmdb' }, { score: 9.6, provider: 'rt' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=400&q=80',
    overview: 'After more than thirty years of service as one of the Navy\'s top aviators, Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot.',
    wikidataDirectorBio: 'Joseph Kosinski'
  },
  {
    id: 'seed_mi_fallout',
    canonicalTitle: 'Mission: Impossible - Fallout',
    type: 'movie',
    year: 2018,
    genres: ['Action', 'Adventure', 'Thriller'],
    ratings: [{ score: 8.5, provider: 'tmdb' }, { score: 9.7, provider: 'rt' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=400&q=80',
    overview: 'Ethan Hunt and his IMF team, along with some familiar allies, race against time after a mission gone wrong.',
    wikidataDirectorBio: 'Christopher McQuarrie'
  },
  {
    id: 'seed_nayakan',
    canonicalTitle: 'Nayakan',
    type: 'movie',
    year: 1987,
    genres: ['Crime', 'Drama'],
    ratings: [{ score: 9.0, provider: 'tmdb' }, { score: 10.0, provider: 'rt' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=400&q=80',
    overview: 'A common man\'s struggle against a corrupt police force leads him to become a powerful don in Mumbai\'s slums.',
    wikidataDirectorBio: 'Mani Ratnam'
  },
  {
    id: 'seed_anbe_sivam',
    canonicalTitle: 'Anbe Sivam',
    type: 'movie',
    year: 2003,
    genres: ['Drama', 'Comedy'],
    ratings: [{ score: 9.2, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=400&q=80',
    overview: 'Two men of contrasting personalities and ideologies embark on a journey from Bhubaneswar to Chennai, finding unexpected bonds along the way.',
    wikidataDirectorBio: 'Sundar C.'
  },
  {
    id: 'seed_pather_panchali',
    canonicalTitle: 'Pather Panchali',
    type: 'movie',
    year: 1955,
    genres: ['Drama'],
    ratings: [{ score: 9.5, provider: 'tmdb' }, { score: 9.8, provider: 'rt' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=400&q=80',
    overview: 'A depiction of rural life in a Bengali village, focusing on the growth and discoveries of young Apu and his sister Durga.',
    wikidataDirectorBio: 'Satyajit Ray'
  },
  {
    id: 'seed_charulata',
    canonicalTitle: 'Charulata',
    type: 'movie',
    year: 1964,
    genres: ['Drama', 'Romance'],
    ratings: [{ score: 9.1, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?auto=format&fit=crop&w=400&q=80',
    overview: 'A lonely young wife of a busy newspaper editor in late 19th-century Bengal finds her intellectual and romantic awakening in her husband\'s cousin.',
    wikidataDirectorBio: 'Satyajit Ray'
  },
  {
    id: 'seed_iruvar',
    canonicalTitle: 'Iruvar',
    type: 'movie',
    year: 1997,
    genres: ['Drama', 'Biography'],
    ratings: [{ score: 9.2, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1524712245354-2c4e5e7134cd?auto=format&fit=crop&w=400&q=80',
    overview: 'An epic tale tracking the friendship and rivalry between a charismatic actor and a passionate writer who rise to define Tamil Nadu\'s political landscape.',
    wikidataDirectorBio: 'Mani Ratnam'
  },
  {
    id: 'seed_kannathil_muthamittal',
    canonicalTitle: 'Kannathil Muthamittal',
    type: 'movie',
    year: 2002,
    genres: ['Drama', 'War'],
    ratings: [{ score: 8.8, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1542204172-e70528091867?auto=format&fit=crop&w=400&q=80',
    overview: 'A young adopted girl journeys to war-torn Sri Lanka to find her biological mother, navigating the emotional depths of identity and belonging.',
    wikidataDirectorBio: 'Mani Ratnam'
  },
  {
    id: 'seed_vaaranam_aayiram',
    canonicalTitle: 'Vaaranam Aayiram',
    type: 'movie',
    year: 2008,
    genres: ['Drama', 'Romance'],
    ratings: [{ score: 8.7, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&w=400&q=80',
    overview: 'An officer reflects on his father\'s profound influence on his life, tracking his youth, heartbreaks, military career, and reconciliation with grief.',
    wikidataDirectorBio: 'Gautham Vasudev Menon'
  },
  {
    id: 'seed_vtv',
    canonicalTitle: 'Vinnaithaandi Varuvaayaa',
    type: 'movie',
    year: 2010,
    genres: ['Romance', 'Drama'],
    ratings: [{ score: 8.5, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1535016120720-40c646be5580?auto=format&fit=crop&w=400&q=80',
    overview: 'An aspiring filmmaker falls deeply in love with a Christian girl from a conservative family, triggering a complex saga of longing and emotional maturity.',
    wikidataDirectorBio: 'Gautham Vasudev Menon'
  },
  {
    id: 'seed_autobiography',
    canonicalTitle: 'Autobiography',
    type: 'movie',
    year: 2004,
    genres: ['Drama', 'Romance'],
    ratings: [{ score: 8.9, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=400&q=80',
    overview: 'A man journeys back to his native village to invite his childhood friends and past loves to his wedding, reflecting on the eras that shaped his heart.',
    wikidataDirectorBio: 'Cheran'
  },
  {
    id: 'seed_kireedam',
    canonicalTitle: 'Kireedam',
    type: 'movie',
    year: 1989,
    genres: ['Drama'],
    ratings: [{ score: 9.4, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=400&q=80',
    overview: 'The tragic tale of Sethumadhavan, whose dreams of becoming a police officer are shattered when he intervenes to save his father from a local gangster.',
    wikidataDirectorBio: 'Sibi Malayil'
  },
  {
    id: 'seed_manichitrathazhu',
    canonicalTitle: 'Manichitrathazhu',
    type: 'movie',
    year: 1993,
    genres: ['Horror', 'Thriller', 'Mystery'],
    ratings: [{ score: 9.5, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=400&q=80',
    overview: 'When a young couple moves into an ancestral mansion rumored to be haunted, a series of uncanny events triggers an investigation by a brilliant psychiatrist.',
    wikidataDirectorBio: 'Fazil'
  },
  {
    id: 'seed_spadikam',
    canonicalTitle: 'Spadikam',
    type: 'movie',
    year: 1995,
    genres: ['Action', 'Drama'],
    ratings: [{ score: 9.0, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=400&q=80',
    overview: 'A youth rebels against his authoritarian father, a school headmaster, growing up to become a hard-edged, logic-defying local rowdy.',
    wikidataDirectorBio: 'Bhadran'
  },
  {
    id: 'seed_oru_vadakkan_veeragatha',
    canonicalTitle: 'Oru Vadakkan Veeragatha',
    type: 'movie',
    year: 1989,
    genres: ['Drama', 'History'],
    ratings: [{ score: 9.3, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=400&q=80',
    overview: 'A revisionist view of the legendary warrior Chandu, framing him not as a traitor but as a victim of family politics and tragic honor.',
    wikidataDirectorBio: 'Hariharan'
  },
  {
    id: 'seed_vidheyan',
    canonicalTitle: 'Vidheyan',
    type: 'movie',
    year: 1994,
    genres: ['Drama'],
    ratings: [{ score: 8.8, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?auto=format&fit=crop&w=400&q=80',
    overview: 'Explores the master-slave dynamic between Thommy, an obedient migrant laborer, and Bhaskara Patelar, an aggressive, abusive landlord.',
    wikidataDirectorBio: 'Adoor Gopalakrishnan'
  },
  {
    id: 'seed_96',
    canonicalTitle: '96',
    type: 'movie',
    year: 2018,
    genres: ['Romance', 'Drama'],
    ratings: [{ score: 8.9, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1524712245354-2c4e5e7134cd?auto=format&fit=crop&w=400&q=80',
    overview: 'Two high school sweethearts meet at a reunion after twenty-two years, navigating the bittersweet space of unfulfilled love.',
    wikidataDirectorBio: 'C. Prem Kumar'
  },
  {
    id: 'seed_meiyazhagan',
    canonicalTitle: 'Meiyazhagan',
    type: 'movie',
    year: 2024,
    genres: ['Drama'],
    ratings: [{ score: 9.0, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1542204172-e70528091867?auto=format&fit=crop&w=400&q=80',
    overview: 'A man returning to his hometown for a family wedding forms an unexpected, emotionally-anchored bond with a relative whose name he cannot recall.',
    wikidataDirectorBio: 'C. Prem Kumar'
  },
  {
    id: 'seed_my_octopus_teacher',
    canonicalTitle: 'My Octopus Teacher',
    type: 'movie',
    year: 2020,
    genres: ['Documentary'],
    ratings: [{ score: 8.7, provider: 'tmdb' }, { score: 9.5, provider: 'rt' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&w=400&q=80',
    overview: 'A filmmaker forges an unusual friendship with an octopus living in a South African kelp forest, learning lessons about the fragility of life.',
    wikidataDirectorBio: 'Pippa Ehrlich, James Reed'
  },
  {
    id: 'seed_free_solo',
    canonicalTitle: 'Free Solo',
    type: 'movie',
    year: 2018,
    genres: ['Documentary'],
    ratings: [{ score: 8.6, provider: 'tmdb' }, { score: 9.7, provider: 'rt' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1535016120720-40c646be5580?auto=format&fit=crop&w=400&q=80',
    overview: 'Alex Honnold attempts to conquer the first free solo climb of El Capitan\'s 3,000-foot vertical rock face in Yosemite National Park.',
    wikidataDirectorBio: 'Elizabeth Chai Vasarhelyi, Jimmy Chin'
  },
  {
    id: 'seed_parasite',
    canonicalTitle: 'Parasite',
    type: 'movie',
    year: 2019,
    genres: ['Thriller', 'Drama', 'Comedy'],
    ratings: [{ score: 9.6, provider: 'tmdb' }, { score: 9.9, provider: 'rt' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=400&q=80',
    overview: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    wikidataDirectorBio: 'Bong Joon Ho'
  },
  {
    id: 'seed_everything_everywhere',
    canonicalTitle: 'Everything Everywhere All at Once',
    type: 'movie',
    year: 2022,
    genres: ['Sci-Fi', 'Adventure', 'Comedy'],
    ratings: [{ score: 9.3, provider: 'tmdb' }, { score: 9.4, provider: 'rt' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=400&q=80',
    overview: 'A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes.',
    wikidataDirectorBio: 'Daniel Kwan, Daniel Scheinert'
  },
  {
    id: 'seed_portrait_lady_fire',
    canonicalTitle: 'Portrait of a Lady on Fire',
    type: 'movie',
    year: 2019,
    genres: ['Romance', 'Drama'],
    ratings: [{ score: 9.4, provider: 'tmdb' }, { score: 9.7, provider: 'rt' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=400&q=80',
    overview: 'On an isolated island in Brittany at the end of the eighteenth century, a female painter is obliged to paint a wedding portrait of a young woman.',
    wikidataDirectorBio: 'Céline Sciamma'
  },
  {
    id: 'seed_get_out',
    canonicalTitle: 'Get Out',
    type: 'movie',
    year: 2017,
    genres: ['Horror', 'Mystery', 'Thriller'],
    ratings: [{ score: 9.0, provider: 'tmdb' }, { score: 9.8, provider: 'rt' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=400&q=80',
    overview: 'A young Afro-American visits his white girlfriend\'s parents for the weekend, where their simmering uneasiness reaches a boiling point.',
    wikidataDirectorBio: 'Jordan Peele'
  }
];

export const SEED_LIBRARY: LibraryItem[] = SEED_MEDIA.map((m, idx) => ({
  mediaId: m.id,
  status: 'to-watch',
  addedAt: Date.now() - idx * 24 * 60 * 60 * 1000, // staggered dates
  updatedAt: Date.now() - idx * 24 * 60 * 60 * 1000
}));
