import { MediaItem, LibraryItem } from '../shared/types';

export const SEED_MEDIA: MediaItem[] = [
  {
    id: 'seed_top_gun_maverick',
    canonicalTitle: 'Top Gun: Maverick',
    type: 'movie',
    year: 2022,
    genres: ['Action', 'Drama'],
    ratings: [{ score: 8.3, provider: 'tmdb' }, { score: 9.6, provider: 'rt' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=400&q=80',
    overview: 'After thirty years, Maverick pushes the envelope as a Navy test pilot.\n\n• Directed by: Joseph Kosinski\n• Starring: Tom Cruise, Miles Teller, Jennifer Connelly\n• Cinematography: Claudio Miranda\n• Music by: Harold Faltermeyer, Hans Zimmer',
    wikidataDirectorBio: 'Joseph Kosinski'
  },
  {
    id: 'seed_mi_fallout',
    canonicalTitle: 'Mission: Impossible - Fallout',
    type: 'movie',
    year: 2018,
    genres: ['Action', 'Adventure', 'Thriller'],
    ratings: [{ score: 8.5, provider: 'tmdb' }, { score: 9.7, provider: 'rt' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=400&q=80',
    overview: 'Ethan Hunt and his IMF team race against time after a mission gone wrong.\n\n• Directed by: Christopher McQuarrie\n• Starring: Tom Cruise, Henry Cavill, Ving Rhames, Simon Pegg\n• Cinematography: Rob Hardy\n• Music by: Lorne Balfe',
    wikidataDirectorBio: 'Christopher McQuarrie'
  },
  {
    id: 'seed_nayakan',
    canonicalTitle: 'Nayakan',
    type: 'movie',
    year: 1987,
    genres: ['Crime', 'Drama'],
    ratings: [{ score: 9.0, provider: 'tmdb' }, { score: 10.0, provider: 'rt' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=400&q=80',
    overview: 'A common man\'s struggle leads him to become a powerful don in Mumbai\'s slums.\n\n• Directed by: Mani Ratnam\n• Starring: Kamal Haasan, Saranya, Karthika\n• Cinematography: P. C. Sreeram\n• Music by: Ilaiyaraaja',
    wikidataDirectorBio: 'Mani Ratnam'
  },
  {
    id: 'seed_anbe_sivam',
    canonicalTitle: 'Anbe Sivam',
    type: 'movie',
    year: 2003,
    genres: ['Drama', 'Comedy'],
    ratings: [{ score: 9.2, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=400&q=80',
    overview: 'Two men of contrasting personalities embark on a journey, finding unexpected bonds.\n\n• Directed by: Sundar C.\n• Starring: Kamal Haasan, Madhavan, Kiran Rathod\n• Cinematography: Arthur A. Wilson\n• Music by: Vidyasagar',
    wikidataDirectorBio: 'Sundar C.'
  },
  {
    id: 'seed_pather_panchali',
    canonicalTitle: 'Pather Panchali',
    type: 'movie',
    year: 1955,
    genres: ['Drama'],
    ratings: [{ score: 9.5, provider: 'tmdb' }, { score: 9.8, provider: 'rt' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=400&q=80',
    overview: 'A depiction of rural life in a Bengali village, focusing on young Apu and Durga.\n\n• Directed by: Satyajit Ray\n• Starring: Subir Banerjee, Kanu Banerjee, Karuna Banerjee\n• Cinematography: Subrata Mitra\n• Music by: Ravi Shankar',
    wikidataDirectorBio: 'Satyajit Ray'
  },
  {
    id: 'seed_charulata',
    canonicalTitle: 'Charulata',
    type: 'movie',
    year: 1964,
    genres: ['Drama', 'Romance'],
    ratings: [{ score: 9.1, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?auto=format&fit=crop&w=400&q=80',
    overview: 'A lonely young wife finds her intellectual and romantic awakening in late 19th-century Bengal.\n\n• Directed by: Satyajit Ray\n• Starring: Madhabi Mukherjee, Soumitra Chatterjee\n• Cinematography: Subrata Mitra\n• Music by: Satyajit Ray',
    wikidataDirectorBio: 'Satyajit Ray'
  },
  {
    id: 'seed_iruvar',
    canonicalTitle: 'Iruvar',
    type: 'movie',
    year: 1997,
    genres: ['Drama', 'Biography'],
    ratings: [{ score: 9.2, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1524712245354-2c4e5e7134cd?auto=format&fit=crop&w=400&q=80',
    overview: 'An epic tale tracking the friendship and rivalry between a charismatic actor and a writer.\n\n• Directed by: Mani Ratnam\n• Starring: Mohanlal, Aishwarya Rai, Prakash Raj\n• Cinematography: Santosh Sivan\n• Music by: A. R. Rahman',
    wikidataDirectorBio: 'Mani Ratnam'
  },
  {
    id: 'seed_kannathil_muthamittal',
    canonicalTitle: 'Kannathil Muthamittal',
    type: 'movie',
    year: 2002,
    genres: ['Drama', 'War'],
    ratings: [{ score: 8.8, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1542204172-e70528091867?auto=format&fit=crop&w=400&q=80',
    overview: 'A young adopted girl journeys to war-torn Sri Lanka to find her biological mother.\n\n• Directed by: Mani Ratnam\n• Starring: Madhavan, Simran, P. S. Keerthana\n• Cinematography: Ravi K. Chandran\n• Music by: A. R. Rahman',
    wikidataDirectorBio: 'Mani Ratnam'
  },
  {
    id: 'seed_vaaranam_aayiram',
    canonicalTitle: 'Vaaranam Aayiram',
    type: 'movie',
    year: 2008,
    genres: ['Drama', 'Romance'],
    ratings: [{ score: 8.7, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&w=400&q=80',
    overview: 'An officer reflects on his father\'s profound influence on his life.\n\n• Directed by: Gautham Vasudev Menon\n• Starring: Suriya, Simran, Sameera Reddy, Divya Spandana\n• Cinematography: R. Rathnavelu\n• Music by: Harris Jayaraj',
    wikidataDirectorBio: 'Gautham Vasudev Menon'
  },
  {
    id: 'seed_vtv',
    canonicalTitle: 'Vinnaithaandi Varuvaayaa',
    type: 'movie',
    year: 2010,
    genres: ['Romance', 'Drama'],
    ratings: [{ score: 8.5, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1535016120720-40c646be5580?auto=format&fit=crop&w=400&q=80',
    overview: 'An aspiring filmmaker falls deeply in love with a Christian girl from a conservative family.\n\n• Directed by: Gautham Vasudev Menon\n• Starring: Silambarasan, Trisha Krishnan\n• Cinematography: Manoj Paramahamsa\n• Music by: A. R. Rahman',
    wikidataDirectorBio: 'Gautham Vasudev Menon'
  },
  {
    id: 'seed_autobiography',
    canonicalTitle: 'Autobiography',
    type: 'movie',
    year: 2004,
    genres: ['Drama', 'Romance'],
    ratings: [{ score: 8.9, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=400&q=80',
    overview: 'A man journeys back to his native village to invite past friends and loves to his wedding.\n\n• Directed by: Cheran\n• Starring: Cheran, Gopika, Mallika, Kanika\n• Cinematography: Vijay Milton\n• Music by: Bharadwaj',
    wikidataDirectorBio: 'Cheran'
  },
  {
    id: 'seed_kireedam',
    canonicalTitle: 'Kireedam',
    type: 'movie',
    year: 1989,
    genres: ['Drama'],
    ratings: [{ score: 9.4, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=400&q=80',
    overview: 'Sethumadhavan\'s dreams of joining the police are ruined when he saves his father from a gangster.\n\n• Directed by: Sibi Malayil\n• Starring: Mohanlal, Thilakan, Parvathy\n• Cinematography: S. Kumar\n• Music by: Johnson',
    wikidataDirectorBio: 'Sibi Malayil'
  },
  {
    id: 'seed_manichitrathazhu',
    canonicalTitle: 'Manichitrathazhu',
    type: 'movie',
    year: 1993,
    genres: ['Horror', 'Thriller', 'Mystery'],
    ratings: [{ score: 9.5, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=400&q=80',
    overview: 'Uncanny events in a haunted mansion trigger an investigation by a psychiatrist.\n\n• Directed by: Fazil\n• Starring: Mohanlal, Shobana, Suresh Gopi\n• Cinematography: Venu\n• Music by: Johnson, M. G. Radhakrishnan',
    wikidataDirectorBio: 'Fazil'
  },
  {
    id: 'seed_spadikam',
    canonicalTitle: 'Spadikam',
    type: 'movie',
    year: 1995,
    genres: ['Action', 'Drama'],
    ratings: [{ score: 9.0, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=400&q=80',
    overview: 'A youth rebels against his authoritarian father, growing up to become a local rowdy.\n\n• Directed by: Bhadran\n• Starring: Mohanlal, Thilakan, Urvashi\n• Cinematography: J. Williams\n• Music by: S. P. Venkatesh',
    wikidataDirectorBio: 'Bhadran'
  },
  {
    id: 'seed_oru_vadakkan_veeragatha',
    canonicalTitle: 'Oru Vadakkan Veeragatha',
    type: 'movie',
    year: 1989,
    genres: ['Drama', 'History'],
    ratings: [{ score: 9.3, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=400&q=80',
    overview: 'A revisionist view of the legendary warrior Chandu, framing him as a victim of tragic honor.\n\n• Directed by: Hariharan\n• Starring: Mammootty, Balan K. Nair, Madhavi\n• Cinematography: Ramachandra Babu\n• Music by: Bombay Ravi',
    wikidataDirectorBio: 'Hariharan'
  },
  {
    id: 'seed_vidheyan',
    canonicalTitle: 'Vidheyan',
    type: 'movie',
    year: 1994,
    genres: ['Drama'],
    ratings: [{ score: 8.8, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?auto=format&fit=crop&w=400&q=80',
    overview: 'Explores the master-slave dynamic between a migrant laborer and a tyrannical landlord.\n\n• Directed by: Adoor Gopalakrishnan\n• Starring: Mammootty, Tanvi Azmi, M. R. Gopakumar\n• Cinematography: Mankada Ravi Varma\n• Music by: Vijay Bhaskar',
    wikidataDirectorBio: 'Adoor Gopalakrishnan'
  },
  {
    id: 'seed_96',
    canonicalTitle: '96',
    type: 'movie',
    year: 2018,
    genres: ['Romance', 'Drama'],
    ratings: [{ score: 8.9, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1524712245354-2c4e5e7134cd?auto=format&fit=crop&w=400&q=80',
    overview: 'Two high school sweethearts meet at a reunion after twenty-two years.\n\n• Directed by: C. Prem Kumar\n• Starring: Vijay Sethupathi, Trisha Krishnan\n• Cinematography: Mahendiran Jayaraju\n• Music by: Govind Vasantha',
    wikidataDirectorBio: 'C. Prem Kumar'
  },
  {
    id: 'seed_meiyazhagan',
    canonicalTitle: 'Meiyazhagan',
    type: 'movie',
    year: 2024,
    genres: ['Drama'],
    ratings: [{ score: 9.0, provider: 'tmdb' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1542204172-e70528091867?auto=format&fit=crop&w=400&q=80',
    overview: 'A man returning to his hometown forms a deep bond with a warm-hearted relative.\n\n• Directed by: C. Prem Kumar\n• Starring: Karthi, Arvind Swamy\n• Cinematography: Mahendiran Jayaraju\n• Music by: Govind Vasantha',
    wikidataDirectorBio: 'C. Prem Kumar'
  },
  {
    id: 'seed_my_octopus_teacher',
    canonicalTitle: 'My Octopus Teacher',
    type: 'movie',
    year: 2020,
    genres: ['Documentary'],
    ratings: [{ score: 8.7, provider: 'tmdb' }, { score: 9.5, provider: 'rt' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&w=400&q=80',
    overview: 'A filmmaker forges an unusual friendship with an octopus living in a kelp forest.\n\n• Directed by: Pippa Ehrlich, James Reed\n• Starring: Craig Foster\n• Cinematography: Roger Horrocks\n• Music by: Kevin Smuts',
    wikidataDirectorBio: 'Pippa Ehrlich, James Reed'
  },
  {
    id: 'seed_free_solo',
    canonicalTitle: 'Free Solo',
    type: 'movie',
    year: 2018,
    genres: ['Documentary'],
    ratings: [{ score: 8.6, provider: 'tmdb' }, { score: 9.7, provider: 'rt' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1535016120720-40c646be5580?auto=format&fit=crop&w=400&q=80',
    overview: 'Alex Honnold attempts to free solo climb the vertical face of El Capitan.\n\n• Directed by: Elizabeth Chai Vasarhelyi, Jimmy Chin\n• Starring: Alex Honnold, Tommy Caldwell\n• Cinematography: Jimmy Chin, Clair Popkin\n• Music by: Marco Beltrami',
    wikidataDirectorBio: 'Elizabeth Chai Vasarhelyi, Jimmy Chin'
  },
  {
    id: 'seed_parasite',
    canonicalTitle: 'Parasite',
    type: 'movie',
    year: 2019,
    genres: ['Thriller', 'Drama', 'Comedy'],
    ratings: [{ score: 9.6, provider: 'tmdb' }, { score: 9.9, provider: 'rt' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=400&q=80',
    overview: 'Greed and class discrimination threaten the relationship between two Korean families.\n\n• Directed by: Bong Joon Ho\n• Starring: Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong\n• Cinematography: Hong Kyung-pyo\n• Music by: Jung Jae-il',
    wikidataDirectorBio: 'Bong Joon Ho'
  },
  {
    id: 'seed_everything_everywhere',
    canonicalTitle: 'Everything Everywhere All at Once',
    type: 'movie',
    year: 2022,
    genres: ['Sci-Fi', 'Adventure', 'Comedy'],
    ratings: [{ score: 9.3, provider: 'tmdb' }, { score: 9.4, provider: 'rt' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=400&q=80',
    overview: 'A Chinese immigrant explores other universes to save existence.\n\n• Directed by: Daniel Kwan, Daniel Scheinert\n• Starring: Michelle Yeoh, Ke Huy Quan, Stephanie Hsu, Jamie Lee Curtis\n• Cinematography: Larkin Seiple\n• Music by: Son Lux',
    wikidataDirectorBio: 'Daniel Kwan, Daniel Scheinert'
  },
  {
    id: 'seed_portrait_lady_fire',
    canonicalTitle: 'Portrait of a Lady on Fire',
    type: 'movie',
    year: 2019,
    genres: ['Romance', 'Drama'],
    ratings: [{ score: 9.4, provider: 'tmdb' }, { score: 9.7, provider: 'rt' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=400&q=80',
    overview: 'On an isolated island in Brittany, a female painter falls in love with her subject.\n\n• Directed by: Céline Sciamma\n• Starring: Noémie Merlant, Adèle Haenel\n• Cinematography: Claire Mathon\n• Music by: Jean-Baptiste de Laubier, Arthur Simonini',
    wikidataDirectorBio: 'Céline Sciamma'
  },
  {
    id: 'seed_get_out',
    canonicalTitle: 'Get Out',
    type: 'movie',
    year: 2017,
    genres: ['Horror', 'Mystery', 'Thriller'],
    ratings: [{ score: 9.0, provider: 'tmdb' }, { score: 9.8, provider: 'rt' }],
    providers: [],
    posterUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=400&q=80',
    overview: 'A young man visits his white girlfriend\'s family estate, uncovering dark secrets.\n\n• Directed by: Jordan Peele\n• Starring: Daniel Kaluuya, Allison Williams, Bradley Whitford\n• Cinematography: Toby Oliver\n• Music by: Michael Abels',
    wikidataDirectorBio: 'Jordan Peele'
  }
];

export const SEED_LIBRARY: LibraryItem[] = SEED_MEDIA.map((m, idx) => ({
  mediaId: m.id,
  status: 'to-watch',
  addedAt: Date.now() - idx * 24 * 60 * 60 * 1000,
  updatedAt: Date.now() - idx * 24 * 60 * 60 * 1000
}));
